#version: "4.40"

services:
  backend:
    build: .
    container_name: Todo-container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
     - ./core:/app
    ports:
     - "8000:8000"
#    environment:
#      - SECRET_KEY=test
#      - DEBUG=True
