# Generated by Django 5.2 on 2025-09-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delete',
        ),
    ]
